#!/usr/bin/env bash
# cluster_down_test.sh — cluster_down.sh must stop the cluster's OWN generated stop_all.sh, and
# must treat "nothing to stop" as success.
#
# The bug this pins: cluster_down.sh used to look for stop_all.sh among the ENGINE scripts. That
# file is generated by build_chain into <outdir>/127.0.0.1/, and the sibling checkout ships no such
# script, so the lookup could only fail -- `fbt cluster down` returned 30 on every correctly
# installed tree, which meant a cluster brought up by `fbt cluster up` could not be stopped by fbt
# at all.
set -euo pipefail
SD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; source "$SD/assert.sh"
CD="$SD/../scripts/cluster_down.sh"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# A workspace laid out the way build_chain leaves one, with a stop_all.sh that records that it ran.
ws="$WORK/cluster"
mkdir -p "$ws/127.0.0.1"
cat > "$ws/127.0.0.1/stop_all.sh" <<'FAKE'
#!/usr/bin/env bash
echo "$PWD" > "$(dirname "$0")/ran"
printf '%s\n' "$@" > "$(dirname "$0")/argv"
FAKE
chmod +x "$ws/127.0.0.1/stop_all.sh"

rc=0
bash "$CD" -o "$ws" >"$WORK/out" 2>&1 || rc=$?
assert_eq "0" "$rc" "a real teardown exits 0 (see $WORK/out)"
assert_eq "0" "$([[ -f "$ws/127.0.0.1/ran" ]] && echo 0 || echo 1)" \
    "the cluster's OWN generated stop_all.sh ran"
# build_chain's stop_all.sh takes no arguments; it stops the nodes beside it. Passing the outdir
# was harmless only because the fake ignored it -- the real one would have been called wrongly.
assert_eq "" "$(cat "$ws/127.0.0.1/argv")" "stop_all.sh is called with no arguments"

# ---- idempotence: the three ways there is nothing to stop ----
rc=0; bash "$CD" -o "$WORK/never-existed" >/dev/null 2>&1 || rc=$?
assert_eq "0" "$rc" "an absent workspace is already stopped"

mkdir -p "$WORK/half"
rc=0; bash "$CD" -o "$WORK/half" >/dev/null 2>&1 || rc=$?
assert_eq "0" "$rc" "a workspace build_chain never laid out is already stopped"

# stop_all.sh exiting non-zero (some nodes already gone) is the steady state this command exists
# to reach, not a failure.
cat > "$ws/127.0.0.1/stop_all.sh" <<'FAKE'
#!/usr/bin/env bash
exit 3
FAKE
chmod +x "$ws/127.0.0.1/stop_all.sh"
rc=0; bash "$CD" -o "$ws" >/dev/null 2>&1 || rc=$?
assert_eq "0" "$rc" "a partially-stopped cluster still exits 0"

assert_done
